<a href="https://colab.research.google.com/github/nachodejuan/50-days-of-data-analysis/blob/main/Day_5_Data_Analytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Array Creation an Vector Operations**

      list_numbers = [[12, 23, -45], [18, -77, -44]]

1. Using NumPy, create an array from the list. Write a code to return all the negative numbers in the list.

In [6]:
import numpy as np

# Define the numbers
list_numbers = [[12, 23, -45], [18, -77, -44]]

# Create the array
arr1 = np.array(list_numbers)

# Return the negative numbers of the list
arr1[arr1<0]

array([-45, -77, -44])

2. Using NumPy, write code to multiply each element in the array you created in question 1 by 2. Create a new variable for this array.

In [7]:
arr2 = 2*arr1
arr2

array([[  24,   46,  -90],
       [  36, -154,  -88]])

3. Write code to calculate the sum of the numbers on axis-1 of the array you created in question 2.

In [8]:
np.sum(arr2, axis = 1)

array([ -20, -206])

4. Write code to calculate the sum of numbers on axis-0 of the array you created in question 2.

In [9]:
np.sum(arr2, axis = 0)

array([  60, -108, -178])

5. Using the NumPy **arange()** function, create a NumPy array of numbers from 0 to 99. The shape of the array must be (2, 5, 10).

In [21]:
# Create the indicated array
arr3 = np.arange(101)

arr3.resize(2,5,10)
arr3

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

6. Write code to slice row [50, 51, 52, 53, 54, 55, 56, 57, 58, 59] from the array above (question 5).

In [24]:
row = arr3[1,0,:]
row

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

7. Let’s analyze the array you created in question 1 further. How many numbers in row 1 are greater than the numbers
in row 2?

In [29]:
# Return the numbers of row 1 which are greater frm the ones of row 2
arr1[0][arr1[0]>arr1[1]]

array([23])