<a href="https://colab.research.google.com/github/nachodejuan/50-days-of-data-analysis/blob/main/Day_2_Data_Analytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Creating and Manipulating Arrays**

1. Write code to import NumPy into your script. Check the version of NumPy installed.

In [3]:
import numpy as np

print(f"The version of NumPy installed is {np.__version__}")

The version of NumPy installed is 1.23.5


2. Here is a list below:

       list1 = [2, 3, 4, 6]

  a) Create a one-dimensional array from the list above. Write another line of code to check the shape and size of your array.

  b) Write a function that takes this array and returns a new array with all the values in the original array reversed.

In [9]:
# Define the list
list1 = [2, 3, 4, 6]

# Create an array from the list above
array1 = np.array(list1)

print(f"The size of the array is: {array1.size}")
print(f"The shape of the array is: {array1.shape}")

The size of the array is: 4
The shape of the array is: (4,)


In [11]:
# Define a function to flip the array
def flip_array(array):
  return np.flip(array, axis = None)

flip_array(array1)

array([6, 4, 3, 2])


3. Given the following lists
  

       list1 = [2, 3, 4, 6]
       list2 = [8, 10, 12, 14]
  
  Create an array from the two lists above. Then write code to check the shape, dimensions, and data type of the array.

In [18]:
# Define the lists
list1 = [2, 3, 4, 6]
list2 = [8, 10, 12, 14]

def create_array(list_1, list_2):
  array1 = np.array([list_1, list_2])
  print(f"The size of the array is: {array1.size}")
  print(f"The shape of the array is: {array1.shape}")
  print(f"The data type of the array is: {array1.dtype}")

create_array(list1, list2)

The size of the array is: 8
The shape of the array is: (2, 4)
The data type of the array is: int64


4. Given the lists
  

       list1 = [2, 3, 4, 6]
       list2 = [8, 10.1, 12, 14]
       list3 = [16, 18, 20, 22.1]

Create an array from the three (3) lists above. Take note that some of the lists contain floats. Create an array that will have an int64 data type.

In [17]:
# Define the lists

list1 = [2, 3, 4, 6]
list2 = [8, 10.1, 12, 14]
list3 = [16, 18, 20, 22.1]

# Create an array from the three lists with data type int64
array1 = np.array([list1, list2, list3], dtype = 'int64')
array1

array([[ 2,  3,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

5. Is it possible to create an array of both floats and integers?

In NumPy, an array is a homogeneous data structure,
which means that it can only hold values of a single datatype. Like we have seen above, if you have a list of floats and integers and you want to convert it to an array, by default it will be converted to the float data type

In [16]:
array2 = np.array(list1+list2+list3)
array2

array([ 2. ,  3. ,  4. ,  6. ,  8. , 10.1, 12. , 14. , 16. , 18. , 20. ,
       22.1])