<a href="https://colab.research.google.com/github/nachodejuan/50-days-of-data-analysis/blob/main/Day_9_Data_Analytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Analyze a One-Dimensional Array**

1. Create a NumPy one-dimensional array with the list below.

          nums = [12, 4, 6, 7, 9, 19, 21, 67, 8]


In [1]:
import numpy as np

# Define the list
nums = [12, 4, 6, 7, 9, 19, 21, 67, 8]

arr1 = np.array(nums)

arr1

array([12,  4,  6,  7,  9, 19, 21, 67,  8])

2. Using NumPy, write code that returns the minimum
number in the array.

In [2]:
np.min(arr1, axis=0)

4

3. Write a code that returns the index of the largest number in the array.

In [5]:
i, = np.where(arr1 == np.max(arr1, axis=0))
i

array([7])

In [10]:
# Useful alternative
max_index = np.argmax(arr1)
max_index

7

4. Using NumPy, calculate the average of the biggest and smallest numbers in the array.

In [6]:
# ptp returns the range of an array

rng = np.ptp(arr1, axis=0)
rng

63

In [7]:
# Returns the range divided by two

rng/2

31.5

5. Write a code to find the mean, median, and standard
deviation of the array.

In [8]:
np.mean(arr1, axis=0), np.median(arr1, axis=0), np.std(arr1, axis=0)

(17.0, 9.0, 18.499249234015476)

6. Write code to find the outlier in the array above.

To find the outlier of the array using NumPy, you can
calculate the lower and upper bounds of the data using the Interquartile Range (IQR) method.

Outliers are defined as any values that are more than 1.5 times the IQR outside of the lower or upper quartile.

We can use the **np.percentile()** function to find the lower and upper quartiles, and then use these values to calculate the IQR, and subsequently the lower and upper bounds.

In [13]:
# Sort the array
sorted_array = np.sort(arr1)
sorted_array

array([ 4,  6,  7,  8,  9, 12, 19, 21, 67])

In [14]:
# Calculate the outlier

def calculate_outlier(array):
  q1 = np.percentile(sorted_array, 25)
  q3 = np.percentile(sorted_array, 75)

  iqr = q3 - q1

  lower_bound = q1 - 1.5 * iqr
  upper_bound = q3 + 1.5 * iqr

  outliers = [x for x in sorted_array if x < lower_bound or x > upper_bound]

  return outliers

calculate_outlier(sorted_array)


[67]