<a href="https://colab.research.google.com/github/nachodejuan/50-days-of-data-analysis/blob/main/Day_6_Data_Analytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Array Manipulation and Vector
Operations**

Given a list:

        list_str = ["23", "12", "90", "28", "30"]

1. Create a NumPy array with the list above. Calculate the standard deviation of the array.

In [2]:
import numpy as np

# Define the list
list_str = ["23", "12", "90", "28", "30"]

# Create the array
arr1 = np.array(list_str, dtype = int)

# Calculate the standard deviation
np.std(arr1)

27.419700946582186

2. Write a code to change the data type of the array you created in question one (1) to a floating data type. Save this as a new variable.

In [ ]:
# Create the float array

arr2 = np.array(list_str, dtype = float)
arr2

array([23., 12., 90., 28., 30.])

3. Write a code to return the sum of values [90.0, 28.0, 30.0] from the array you just created in question (3).

In [ ]:
# Return the indicated slice
arr2[2:]

array([90., 28., 30.])

4. Create a 2-dimensional array of random integers from 0 to 100 with the shape (5, 5). Use the array to find the minimum and maximum values, as well as the mean and standard deviation. Ensure that the results are reproducible.

In [ ]:
# Generate random data
rng = np.random.default_rng(seed = 24)

arr3 = rng.integers(low=0, high=101, size=(5, 5))
arr3

array([[38, 33, 75, 40, 79],
       [58, 12, 51, 41, 56],
       [58, 57, 57, 88, 33],
       [ 8, 69, 74, 46, 82],
       [28, 71, 66, 41, 79]])

In [ ]:
# Get the maximum
np.max(arr3)

88

In [ ]:
# Get the minimum
np.min(arr3)

8

In [ ]:
# Get the deviation
np.std(arr3)

21.014280858501916

In [ ]:
# Get the mean
np.mean(arr3)

53.6

5. Given two arrays:

        first_names = ["John", " Kenny"]
        last_names = ["Smith", " Sakula"]


Using NumPy’s char.join() function, create two arrays by joining the first name with the last name. Your first array should be: array(['John', 'Smith'], dtype='U6'). Your second array should be: array(['Kenny', 'Sakula'], dtype='U6').

In [10]:
# Define the two arrays
first_names = ["John", " Kenny"]
last_names = ["Smith", " Sakula"]

# Using the join function to create an array
arr = np.char.join("", [first_names, last_names])

arr1 = arr[:,0]
arr2 = arr[:,1]

arr1, arr2

(array(['John', 'Smith'], dtype='<U7'),
 array([' Kenny', ' Sakula'], dtype='<U7'))